### PR TITLE
MAKE IT RAIN

### PR DESCRIPTION
**Pull request by Legoben**
"What a horrible screenshot"

### CODE REVIEW

**Comment by simplyluke** [comment]
this will cause conflicts with 0.2 but this is amazing :+1:

**Comment by aroman** [comment]
can confirm, this is fucking awesome. can we put this at a separate URL or something? like /alpha.html?

**Comment by simplyluke** [comment]
Yes. I'll do it tomorrow.

On Saturday, July 26, 2014, Avi Romanoff notifications@github.com wrote:

> can confirm, this is fucking awesome. can we put this at a separate URL or
> something? like /alpha.html?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aroman/PennAppsApps/pull/8#issuecomment-50224684.

## 

Luke Wright
simplyluke.com

**Comment by aroman** [comment]
:+1:

**Comment by Legoben** [comment]
We could add it to the main page and make it call createRain() when the user gets rejected?

**Comment by simplyluke** [comment]
YESSSSSSSSS :cloud:

**Comment by aroman** [comment]
👌👌👌👌👌

**Comment by Legoben** [comment]
I'll close this and make a new pull request when it's ready :smile:

**Comment by simplyluke** [comment]
Hey, I just implemented it

## 

Luke Wright
luke@simplyluke.com

**Comment by Legoben** [comment]
Oh, awesome :satisfied:

**Pull request closed without merging**
